name: Beta
on:
  push:
    branches:
      - master

jobs:
  android-beta:
    name: Android Beta
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Checkout keys
        uses: actions/checkout@v2
        with:
          repository: omapsapp/omapsapp-release-keys
          path: private/release
          ref: release
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Remove old outputs
        shell: bash
        run: |
          rm -rf android/build/outputs/

      - name: Configure
        shell: bash
        run: |
          ./configure.sh release

      - name: Compile
        shell: bash
        working-directory: android
        run: |
          export PATH="$(dirname $ANDROID_SDK_ROOT/cmake/*/bin/.|tail -n1):$PATH" # Use CMake from SDK
          echo $PATH
          cmake --version
          ninja --version
          ./gradlew -PsplitApk=true -x lint -x lintVitalWebBeta assembleWebBeta uploadCrashlyticsSymbolFileWebBeta

      - name: Upload arm64-v8a beta apk
        uses: actions/upload-artifact@v2
        with:
          name: android-web-arm64-v8a-beta
          path: android/build/outputs/apk/android-web-arm64-v8a-beta-*.apk
          if-no-files-found: error

      - name: Upload armeabi-v7a beta apk
        uses: actions/upload-artifact@v2
        with:
          name: android-web-armeabi-v7a-beta
          path: android/build/outputs/apk/android-web-armeabi-v7a-beta-*.apk
          if-no-files-found: error

      - name: Upload x86_64 beta apk
        uses: actions/upload-artifact@v2
        with:
          name: android-web-x86_64-beta
          path: android/build/outputs/apk/android-web-x86_64-beta-*.apk
          if-no-files-found: error

      - name: Upload x86 beta apk
        uses: actions/upload-artifact@v2
        with:
          name: android-web-x86-beta
          path: android/build/outputs/apk/android-web-x86-beta-*.apk
          if-no-files-found: error

      - name: Upload arm64-v8a to App Distribution
        shell: bash
        working-directory: android
        run: |
           git --no-pager show -s --format='%s%n%n%b' HEAD > RELEASE
           # Sic: Firebase App Distribution doesn't support splits
           (cd ./build/outputs/apk; ln -s android-web-arm64-v8a-beta-*.apk android-web-arm64-v8a-beta.apk)
           ./gradlew appDistributionUploadWebBeta
