name: Android Release
on:
  push:
    tags:
      - '202[0-9].[0-9]+.[0-9]+-[0-9]+-android' # 2021.08.03-1-android

jobs:
  android-release:
    name: Android Release
    runs-on: ubuntu-latest
    environment: production
    strategy:
      fail-fast: false
      matrix:
        include:
          - flavor: google
          - flavor: huawei
          - flavor: web
    steps:
      - name: Install build tools and dependencies
        shell: bash
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Parallel submodules checkout
        shell: bash
        run: git submodule update --init --recursive --jobs=$(($(nproc) * 2))

      - name: Checkout private keys
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.PRIVATE_REPO }}
          ssh-key: ${{ secrets.PRIVATE_SSH_KEY }}
          ref: master
          path: private.git

      - name: Configure repo with private keys
        shell: bash
        run: |
          ./configure.sh ./private.git
          rm -rf ./private.git

      - name: Set up SDK
        shell: bash
        run: (cd tools/android; ./set_up_android.py --sdk $ANDROID_SDK_ROOT)

      - name: Compile and upload to Google Play
        shell: bash
        working-directory: android
        run: |
          ./gradlew bundleGoogleRelease publishGoogleReleaseBundle
        if: ${{ matrix.flavor == 'google' }}

      - name: Compile and upload to Huawei AppGallery
        shell: bash
        working-directory: android
        run: |
          ./gradlew bundleHuaweiRelease
          ./gradlew publishHuaweiAppGalleryHuaweiRelease
        if: ${{ matrix.flavor == 'huawei' }}

      - name: Compile universal APK
        shell: bash
        working-directory: android
        run: |
          ./gradlew assembleWebRelease
        if: ${{ matrix.flavor == 'web' }}

      - name: Upload universal APK to GitHub
        uses: actions/upload-artifact@v2
        if: ${{ matrix.flavor == 'web' }}
        with:
          name: web-release-apk
          path: ./android/build/outputs/apk/web/release/OrganicMaps-*-web-release.apk
          if-no-files-found: error
