name: Beta
on:
  push:
    branches:
      - master

jobs:
  android-beta:
    name: Android Beta
    runs-on: [self-hosted, linux, X64]
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Remove old outputs
        shell: bash
        run: |
          rm -rf android/build/outputs/

      - name: Configure
        shell: bash
        run: |
          ./configure.sh release

      - name: Set up SDK
        shell: bash
        run: |
          (cd tools/android; ./set_up_android.py --sdk $ANDROID_SDK_ROOT= --ndk $ANDROID_NDK_ROOT)

      - name: Compile
        shell: bash
        working-directory: android
        run: ./gradlew -PsplitApk=true -x lint -x lintVitalWebBeta assembleWebBeta uploadCrashlyticsSymbolFileWebBeta

      - name: Upload arm64-v8a beta apk
        uses: actions/upload-artifact@v2
        with:
          name: android-web-arm64-v8a-beta
          path: android/build/outputs/apk/android-web-arm64-v8a-beta-*.apk
          if-no-files-found: error

      - name: Upload armeabi-v7a beta apk
        uses: actions/upload-artifact@v2
        with:
          name: android-web-armeabi-v7a-beta
          path: android/build/outputs/apk/android-web-armeabi-v7a-beta-*.apk
          if-no-files-found: error

      - name: Upload x86_64 beta apk
        uses: actions/upload-artifact@v2
        with:
          name: android-web-x86_64-beta
          path: android/build/outputs/apk/android-web-x86_64-beta-*.apk
          if-no-files-found: error

      - name: Upload x86 beta apk
        uses: actions/upload-artifact@v2
        with:
          name: android-web-x86-beta
          path: android/build/outputs/apk/android-web-x86-beta-*.apk
          if-no-files-found: error

      - name: Upload arm64-v8a to App Distribution
        shell: bash
        working-directory: android
        run: |
           git --no-pager show -s --format='%s%n%n%b' HEAD > RELEASE
           # Sic: Firebase App Distribution doesn't support splits
           (cd ./build/outputs/apk; ln -s android-web-arm64-v8a-beta-*.apk android-web-arm64-v8a-beta.apk)
           ./gradlew appDistributionUploadWebBeta
