name: Android Monkey
on:
  push: # Please don't change to pull_request because it can expose secrets
    branches:
      - master
    paths-ignore:
    - .github/workflows/android-release*
    - .github/workflows/android-check*
    - .github/workflows/android-beta*
    - .github/workflows/linux*
    - '**/*_tests/**'
    - '**/CMakeLists.txt'
    - CONTRIBUTORS
    - LICENSE
    - NOTICE
    - README.md
    - iphone/**
    - xcode/**
    - docs/**
    - generator/**
    - packaging/**
    - pyhelpers/**
    - qt*/**
    - skin_generator/**
    - track_generator/**

jobs:
  android-google-debug:
    name: Android Google Debug
    runs-on: ubuntu-latest
    environment: beta
    steps:
      - name: Install build tools and dependencies
        shell: bash
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install Google SDK
        uses: google-github-actions/setup-gcloud@master

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Parallel submodules checkout
        shell: bash
        run: git submodule update --init --recursive --jobs=$(($(nproc) * 2))

      - name: Checkout private keys
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.PRIVATE_REPO }}
          ssh-key: ${{ secrets.PRIVATE_SSH_KEY }}
          ref: master
          path: private.git

      - name: Configure repo with private keys
        shell: bash
        run: |
          ./configure.sh ./private.git
          rm -rf ./private.git

      - name: Set up SDK
        shell: bash
        run: (cd tools/android; ./set_up_android.py --sdk $ANDROID_SDK_ROOT)

      - name: Compile
        shell: bash
        working-directory: android
        run: |
          cmake --version
          ninja --version
          ./gradlew -Parm64 -Parm32 -Pfirebase assembleGoogleDebug

      - name: Run monkey
        run: |
          gcloud auth activate-service-account --key-file android/firebase-test-lab.json
          gcloud config set project omapsapp
          gcloud firebase test android run --app ./android/build/outputs/apk/google/debug/OrganicMaps-*-google-debug.apk \
            --device model=redfin,version=30 \
            --device model=a10,version=29 \
            --device model=dipper,version=28 \
            --device model=OnePlus3T,version=26 \
            --device model=flo,version=21,orientation=landscape \
            --timeout 15m
