name: Check
on:
  pull_request:

jobs:
  android-check:
    name: Android Check
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Parallel submodules checkout
        shell: bash
        run: |
          git submodule update --init --recursive --jobs=10

      - name: Configure in Open Source mode
        shell: bash
        run: |
          ./configure.sh

      - name: Set up SDK
        shell: bash
        run: |
          (cd tools/android; ./set_up_android.py --sdk $ANDROID_SDK_ROOT)

      - name: Compile
        shell: bash
        working-directory: android
        run: |
          export PATH="$(dirname $ANDROID_SDK_ROOT/cmake/*/bin/.|tail -n1):$PATH" # Use CMake from SDK
          echo $PATH
          cmake --version
          ninja --version
          ./gradlew -Parm64 assembleWebDebug

      - name: Upload arm64-v8a debug apk
        uses: actions/upload-artifact@v2
        with:
          name: android-web-arm64-v8a-debug
          path: android/build/outputs/apk/android-web-debug-*.apk
          if-no-files-found: error
