name: iOS Check
on:
  pull_request:
    paths-ignore:
    - .github/workflows/android*
    - .github/workflows/linux*
    - '**/*_tests/**'
    - '**/CMakeLists.txt'
    - CONTRIBUTORS
    - LICENSE
    - NOTICE
    - README.md
    - android/**
    - docs/**
    - generator/**
    - packaging/**
    - pyhelpers/**
    - qt*/**
    - skin_generator/**
    - track_generator/**

jobs:
  ios-check:
    name: Build iOS Debug
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Parallel submodules checkout
        shell: bash
        run: git submodule update --init --recursive --jobs=4

      - name: Configure
        shell: bash
        run: ./configure.sh

      - name: Compile
        shell: bash
        # Just check compilation
        run: |
          # Run twice as a workaround for a dependency problem.
          # https://github.com/omapsapp/omapsapp/issues/133
          xcodebuild \
            -workspace xcode/omim.xcworkspace \
            -scheme OMaps \
            -configuration Debug build \
            'generic/platform=iOS' \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
          |xcpretty || true
          xcodebuild \
            -workspace xcode/omim.xcworkspace \
            -scheme OMaps \
            -configuration Debug build \
            'generic/platform=iOS' \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
          |xcpretty
