name: Linux Check
on:
  workflow_dispatch: # Manual trigger
  pull_request:
    paths-ignore:
      - .gitignore
      - .github/**
      - CONTRIBUTORS
      - LICENSE
      - NOTICE
      - README.md
      - android/**
      - iphone/**
      - xcode/**
      - docs/**
      - packaging/**
      - pyhelpers/**

jobs:
  linux-debug:
    name: Linux Debug and Release Build and Test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        compiler: [{ CXX: g++-10, CC: gcc-10 }, { CXX: clang++-12, CC: clang-12 }]
        params: [{ CMAKE_BUILD_TYPE: Debug }, { CMAKE_BUILD_TYPE: Release }]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Parallel submodules checkout
        shell: bash
        run: git submodule update --init --recursive --jobs=$(($(nproc) * 2))

      - name: Install build tools and dependencies
        shell: bash
        run: |
          sudo apt update -y
          sudo apt install -y \
              ninja-build \
              qtbase5-dev \
              libqt5svg5-dev \
              clang-tools-11

      - name: Configure
        shell: bash
        run: ./configure.sh

      - name: CMake
        shell: bash
        env:
          CC: ${{ matrix.compiler.CC }}
          CXX: ${{ matrix.compiler.CXX }}
        # -g1 should slightly reduce build time.
        run: |
          echo "Building ${{ matrix.params.CMAKE_BUILD_TYPE }}"
          cmake . -B build -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.params.CMAKE_BUILD_TYPE }} -DCMAKE_CXX_FLAGS_DEBUG=-g1

      - name: Compile
        shell: bash
        working-directory: build
        run: ninja

      - name: Checkout world_feed_integration_tests_data
        uses: actions/checkout@v2
        with:
          repository: omapsapp/world_feed_integration_tests_data
          path: data/world_feed_integration_tests_data

      - name: Tests
        shell: bash
        # generator_integration_tests - https://github.com/organicmaps/organicmaps/issues/225
        # routing_integration_tests - https://github.com/organicmaps/organicmaps/issues/221
        # routing_quality_tests - https://github.com/organicmaps/organicmaps/issues/215
        # drape_tests - requires X Window

        # Separate run of OH boost-based test
        run: |
          ./build/opening_hours_tests |
          ./tools/python/run_desktop_tests.py \
            -f ./build \
            -u ./data \
            -d ./data \
            -e generator_integration_tests \
            -e routing_integration_tests \
            -e routing_quality_tests \
            -e world_feed_integration_tests \
            -e drape_tests \
            -e shaders_tests \
                            \
            -e opening_hours_tests \
            -e opening_hours_integration_tests \
            -e routing_consistency_tests \
            -e opening_hours_supported_features_tests \
            -e storage_integration_tests \
